# Generated by Django 5.0.3 on 2024-04-15 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_match', '0002_initial'),
        ('core_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='prev_round_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_round_1_to_next_rounds', to='core_tournament.round'),
        ),
        migrations.AddField(
            model_name='round',
            name='prev_round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_round_2_to_next_rounds', to='core_tournament.round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='next_match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_match_for_round', to='core_match.match'),
        ),
        migrations.AlterField(
            model_name='round',
            name='next_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_rounds_from_prev_round', to='core_tournament.round'),
        ),
    ]
