# Generated by Django 5.0.3 on 2026-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
