# Generated by Django 5.0.3 on 2024-07-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='final_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_final_round', to='core_tournament.round'),
        ),
    ]
