# Generated by Django 5.0.3 on 2024-04-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
