# Generated by Django 5.0.3 on 2024-04-18 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0002_round_prev_round_1_round_prev_round_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='match_2',
        ),
        migrations.RemoveField(
            model_name='round',
            name='next_match',
        ),
        migrations.AddField(
            model_name='round',
            name='player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_player_1', to='core_tournament.player'),
        ),
        migrations.AddField(
            model_name='round',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_player_2', to='core_tournament.player'),
        ),
        migrations.AddField(
            model_name='round',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_winner', to='core_tournament.player'),
        ),
    ]
