# Generated by Django 5.0.3 on 2024-10-15 20:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_tournament", "0003_rename_invitedplayer_invite"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(old_name="Invite", new_name="InvitePlayer",),
    ]
