# Generated by Django 5.0.3 on 2024-04-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0003_tournament_final_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='invited_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='invited_players',
            field=models.ManyToManyField(blank=True, related_name='invited_tournaments', to='core_tournament.invitedplayer'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='participating_tournaments', to='core_tournament.player'),
        ),
    ]
