# Generated by Django 5.0.3 on 2024-04-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0004_remove_tournament_created_remove_tournament_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='seed',
            field=models.IntegerField(null=True),
        ),
    ]
