# Generated by Django 5.0.3 on 2024-04-22 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0005_alter_player_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='invited_players',
            field=models.ManyToManyField(blank=True, default=[], related_name='invited_tournaments', to='core_tournament.invitedplayer'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, default=[], related_name='participating_tournaments', to='core_tournament.player'),
        ),
    ]
