# Generated by Django 5.0.3 on 2024-04-22 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0006_alter_tournament_invited_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='invited_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
        migrations.AddField(
            model_name='tournament',
            name='invited_players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_invited_players', to='core_tournament.invitedplayer'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_players', to='core_tournament.player'),
        ),
    ]
