# Generated by Django 5.0.3 on 2024-04-22 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0008_alter_tournament_invited_players_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='invited_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='players',
        ),
    ]
