# Generated by Django 5.0.3 on 2024-04-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0009_remove_tournament_invited_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedplayer',
            name='accepted_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='invitedplayer',
            name='invited_date',
            field=models.DateTimeField(null=True),
        ),
    ]
