# Generated by Django 5.0.3 on 2024-06-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0010_alter_invitedplayer_accepted_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='invitedplayer',
            table='core_invited_player',
        ),
        migrations.AlterModelTable(
            name='player',
            table='core_player',
        ),
    ]
