# Generated by Django 5.0.3 on 2024-07-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0011_alter_invitedplayer_table_alter_player_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='end_date',
        ),
    ]
