# Generated by Django 5.0.3 on 2024-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tournament', '0012_remove_tournament_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedplayer',
            name='state',
            field=models.CharField(default='sent', max_length=20),
        ),
    ]
