"""
Django settings for CoreRoot project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
import dj_database_url
from django.core.exceptions import ImproperlyConfigured

def get_token_serializer():
    from core.user.serializers import CustomTokenObtainPairSerializer
    return CustomTokenObtainPairSerializer

load_dotenv()

# Force IPv4 for all outbound DNS resolution. Railway (and some other
# cloud platforms) only route IPv4 from containers — but DNS still
# returns AAAA records for hosts like smtp.gmail.com, so Python tries
# the IPv6 address first and the connect() fails with
# "Network is unreachable" before falling back to the IPv4.
#
# Set FORCE_IPV4_OUTBOUND=True on services that need this (the worker
# for sure; the web service if it makes any outbound calls). Leave
# unset locally where IPv6 works fine.
if os.environ.get('FORCE_IPV4_OUTBOUND', '').strip().lower() in ('1', 'true', 'yes', 'on'):
    import socket as _socket
    _real_getaddrinfo = _socket.getaddrinfo

    def _ipv4_only_getaddrinfo(host, port, family=0, *args, **kwargs):
        return _real_getaddrinfo(host, port, _socket.AF_INET, *args, **kwargs)

    _socket.getaddrinfo = _ipv4_only_getaddrinfo

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!

if os.environ.get('DEBUG') == 'True':
    DEBUG = True
else:
    DEBUG = False

# When True, bypasses (a) per-league refresh cadence, (b) per-event odds-cache
# TTL, and (c) the per-event monthly refresh cap. Only flip on for local
# development against the simulator — in prod every cron tick would otherwise
# hammer the API. Off by default.
EVENTS_DEBUG_FORCE_FRESH = os.environ.get("EVENTS_DEBUG_FORCE_FRESH") == "True"

ALLOWED_HOSTS = [h for h in os.environ.get("ALLOWED_HOSTS", '').split(',') if h]
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1', 'testserver']

# Production-deployment guardrails — fail loudly at boot if the deployer
# forgot to set required env values. Mirrors Django's deployment checklist
# but as a hard error instead of a runtime check (which only shows up when
# something tries to render a CSRF cookie or sign a session).
if not DEBUG:
    if not SECRET_KEY:
        raise RuntimeError(
            "SECRET_KEY must be set in production. Generate one with: "
            "python -c \"import secrets; print(secrets.token_urlsafe(64))\""
        )
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            "ALLOWED_HOSTS must be a non-empty comma-separated list in "
            "production (e.g. ALLOWED_HOSTS=mdproject.example.com)"
        )

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=15),
}

CORS_ALLOW_HEADERS = [
    'access-control-allow-origin',
    'content-type',
    'authorization',
    'x-csrftoken',
]


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH']
CORS_ALLOW_ALL_ORIGINS = False

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # must come before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'axes',  # brute-force lockout on auth views (S-9)
    # Admin 2FA (plan §7.3 item 9 phase 1) — TOTP devices + OTPAdminSite.
    # Enforcement is flag-gated via ADMIN_REQUIRE_OTP (see CoreRoot/urls.py);
    # apps/middleware stay on unconditionally so devices can be enrolled
    # BEFORE the flag flips (otherwise: instant admin lockout).
    'django_otp',
    'django_otp.plugins.otp_totp',
    "django_celery_results",  # Dead post-Procrastinate cutover; kept so old core_crons migrations replay on fresh DBs.
    "django_celery_beat",     # Dead post-Procrastinate cutover; kept for the same reason.
    "procrastinate.contrib.django",
    "storages",
    "anymail",
    'crispy_forms',
    'crispy_bootstrap5',
               # This was in the first list only

    # MDProject Models
    'core.commands',
    'core',
    'core.user',
    'core.auth',
    'core.crons',
    'core.event',
    'core.game',
    'core.match',
    'core.tournament',
    'core.mail',
    'core.web',
    'core.portal',
    'core.billing',
    'core.metrics',  # In-house product analytics (roadmap Phase 3) — ProductEvent + track()
    'core.api',  # Portal JSON API (v1) — secure islands surface (plan js-portal-security)

    # Custom admin app configuration
    'core.admin.CoreAdminConfig',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # CSP header (S-7) — enforced (see CONTENT_SECURITY_POLICY below). Sits high
    # so the header is attached to every response.
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # OTP device verification — must follow AuthenticationMiddleware.
    # Populates request.user.is_verified(); OTPAdminSite relies on it.
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # Sets ``X-Robots-Tag: noindex, nofollow, noarchive`` on every response
    # whose path isn't on the public-marketing whitelist. Defense-in-depth
    # against crawlers that don't respect robots.txt.
    'core.middleware.noindex.NoIndexPrivateRoutesMiddleware',
    # Redirects anonymous visitors away from /web/portal/* and /admin/*
    # back to the public landing page (instead of showing /auth/login/
    # or a Django 404). Must run AFTER AuthenticationMiddleware so
    # ``request.user`` is populated.
    'core.middleware.portal_auth_redirect.AnonymousPortalRedirectMiddleware',
    # Aggrigator-profile passthrough. No-op unless
    # AGGRIGATOR_PROFILE_PASSTHROUGH=True AND the inbound request carries
    # the X-Profile-Aggrigator: 1 header. When triggered, replaces the
    # portal HTML response with the captured aggrigator flame graph(s).
    # See core/middleware/profile_passthrough.py.
    'core.middleware.profile_passthrough.ProfilePassthroughMiddleware',
    # django-axes (S-9) — MUST be last: it wraps the auth flow and returns the
    # lockout response. Needs request.user, so it sits after AuthenticationMiddleware.
    'axes.middleware.AxesMiddleware',
]

# Aggrigator profile-passthrough feature flag. When True, the
# ProfilePassthroughMiddleware enables the X-Profile-Aggrigator header
# handoff. Default off — costs nothing when disabled, but a stray header
# in prod with this flag on would replace real portal pages with
# pyinstrument HTML. Pair with AGG_PROFILER_ENABLED=True on the
# aggrigator side.
AGGRIGATOR_PROFILE_PASSTHROUGH = (
    os.environ.get("AGGRIGATOR_PROFILE_PASSTHROUGH", "").strip().lower()
    in ("1", "true", "yes", "on")
)




ROOT_URLCONF = 'CoreRoot.urls'

BASE_DIR_TEMPS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR_TEMPS,'core', 'admin', 'templates',)],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Reject framing by other origins. Per plan §2.3 (A05). Was 'ALLOWALL', a
# clickjacking risk. Switch to 'SAMEORIGIN' if any first-party iframe surface
# turns up; otherwise leave as DENY.
X_FRAME_OPTIONS = 'DENY'


WSGI_APPLICATION = 'CoreRoot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Postgres lives on Neon (off-Railway), so every fresh connection pays a
# ~30ms transcontinental TLS handshake. Two layers of pooling mitigate
# that:
#   1. dj_database_url(conn_max_age=600) — each gunicorn / celery worker
#      keeps its PG connection warm for 10min between requests instead of
#      reconnecting every 60s.
#   2. CONN_HEALTH_CHECKS=True (Django 4.1+) — pings the connection
#      before each request and reconnects on dead-conn errors. Without
#      it, Neon idle-timing a pooled connection causes the next request
#      to 500 instead of transparently retrying.
#
# DISABLE_SERVER_SIDE_CURSORS is required when the DATABASE_URL points at
# Neon's PgBouncer-pooled endpoint (transaction mode) — named server-side
# cursors break under transaction pooling because the named cursor lives
# in a different physical connection than the next FETCH.
#
# IMPORTANT: DATABASE_URL on Railway should point at Neon's *pooled*
# hostname (the one with "-pooler" in it, e.g.
# ep-cool-name-12345-pooler.us-east-2.aws.neon.tech), NOT the direct
# endpoint. Pooled = up to 10k connections multiplexed; direct = 1
# physical connection per client, which exhausts under any real traffic.
DATABASES = {
    'default': dj_database_url.config(
        default=f"{os.environ.get('DATABASE_URL')}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}
DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True

DATABASES['default']['TEST'] = {
    'SERIALIZE': True,
}



# ---------------------------------------------------------------------------
# Email — Resend over HTTPS via django-anymail.
#
# We send transactional mail through Resend's REST API (port 443) instead of
# SMTP because Railway (and most cloud platforms) block outbound SMTP from
# containers. The previous SMTP config is retired; if a future deployment
# needs SMTP, override EMAIL_BACKEND via env and re-add the SMTP settings.
# ---------------------------------------------------------------------------
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND', 'anymail.backends.resend.EmailBackend',
)
ANYMAIL = {
    "RESEND_API_KEY": os.environ.get('RESEND_API_KEY', ''),
}
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', 'noreply@warforaterra.com',
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL
# Cap socket time so a misbehaving HTTPS round-trip can't pin a worker.
EMAIL_TIMEOUT = 30

# Public-facing site URL — used in email templates to build absolute URLs
# for the logo and any in-email links. Email clients can't resolve
# relative paths, so we baseline this once and pass it into every
# template via the send_email task.
#
# Resolution order (first match wins):
#   1. SITE_URL env var (explicit override, e.g. for staging)
#   2. RAILWAY_PUBLIC_DOMAIN — auto-populated by Railway. Reflects the
#      Railway-generated *.up.railway.app domain by default, and the
#      attached custom domain (e.g. warforaterra.com) once one is set
#      in the service's Networking tab. No app-level config needed.
#   3. ALLOWED_HOSTS[0] — fallback for non-Railway hosts.
#   4. http://localhost:8000 — last-resort for local shells / mgmt cmds.
def _derive_site_url() -> str:
    explicit = (os.environ.get('SITE_URL') or '').strip().rstrip('/')
    if explicit:
        return explicit
    railway = (os.environ.get('RAILWAY_PUBLIC_DOMAIN') or '').strip().rstrip('/')
    if railway:
        # Railway gives us a bare hostname; emails need a scheme.
        return f"https://{railway}"
    for host in ALLOWED_HOSTS:
        host = host.strip()
        if host and host != '*':
            scheme = 'http' if (DEBUG or host in ('localhost', '127.0.0.1')) else 'https'
            return f"{scheme}://{host}"
    return 'http://localhost:8000'


SITE_URL = _derive_site_url()
EMAIL_LOGO_URL = os.environ.get(
    'EMAIL_LOGO_URL',
    f"{SITE_URL}/static/assets/Logo/paradise_logo_2_normal.png",
)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Argon2 is the modern Django-recommended hasher; PBKDF2 stays second so
# existing hashes still verify. Django automatically re-hashes a user's
# password to the first hasher on their next successful login. Per plan §2.3
# (A02). Requires ``argon2-cffi`` (already pulled in transitively by other
# packages; explicit pin is in requirements.txt).
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]

AUTH_USER_MODEL = 'core_user.User'


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AWS_ACCESS_KEY_ID = os.getenv('BUCKETEER_AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('BUCKETEER_AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('BUCKETEER_BUCKET_NAME')
AWS_S3_REGION_NAME = os.getenv('BUCKETEER_AWS_REGION')
AWS_S3_CUSTOM_DOMAIN = (
    f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
    if AWS_STORAGE_BUCKET_NAME
    else None
)
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
AWS_QUERYSTRING_AUTH = False
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None
AWS_S3_SIGNATURE_VERSION = 's3v4'

# Configure Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_TOKEN_CLASSES': (
        'CoreRoot.settings.get_token_serializer',
    ),
    # Throttle RATES only (fixes S-9, API side). The throttle CLASSES are applied
    # per-view via core.api.base.V1ViewMixin (user/anon) and opt-in classes
    # (LiveOddsRateThrottle, AuthSensitiveRateThrottle) — NOT globally, so the
    # legacy /api/ endpoints' behavior is unchanged until they migrate. Counters
    # use the default DatabaseCache; see core/api/throttling.py.
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '600/min',
        'live_odds': '60/min',
        'auth_sensitive': '10/min',
    },
}

AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend MUST be first: it short-circuits with PermissionDenied
    # when the (IP, username) pair is locked, then falls through (returns None) to
    # the real backend when it isn't. It does NOT authenticate by itself.
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',  # Keep the default model backend
]

# ---------------------------------------------------------------------------
# django-axes (S-9) — brute-force / credential-stuffing brake on the
# server-rendered auth views (login + admin login). Locks the (IP, username)
# pair after AXES_FAILURE_LIMIT failures for AXES_COOLOFF_TIME, then auto-clears.
# The v1 JSON API is throttled separately (core/api/throttling.py).
# ---------------------------------------------------------------------------
AXES_FAILURE_LIMIT = 10
AXES_COOLOFF_TIME = timedelta(minutes=15)
# Lock by SOURCE IP only. Rationale: (a) it's consistent — axes can't reliably
# capture the username from this login flow (it stores NULL), so an (ip, username)
# key would record under NULL but check under the real username, letting an
# attacker bypass the lock with valid-format input; (b) IP-only locks the
# *attacker's* source, never a username globally, so it can't be used to lock a
# specific victim out (the targeted-DoS the combo key was meant to avoid). The
# only cost is shared-NAT collateral, acceptable for this app and bounded by the
# 15-min cooloff. Real client IP comes from the proxy settings below.
AXES_LOCKOUT_PARAMETERS = ["ip_address"]
AXES_RESET_ON_SUCCESS = True   # a good login clears the failure counter
AXES_HTTP_RESPONSE_CODE = 429  # "rate limited", not 403
AXES_ENABLE_ADMIN = True       # review/reset lockouts from Django admin
AXES_VERBOSE = True
# Real client IP behind Cloudflare → Coolify/Traefik. REMOTE_ADDR is always
# Traefik, and X-Forwarded-For depends on Traefik's trust config, so axes
# resolves the IP via core.ip.get_client_ip (CF-Connecting-IP → XFF last
# hop → REMOTE_ADDR). NOTE: the AXES_IPWARE_* settings this replaces were
# silently inert — axes 6+ only reads them when the optional django-ipware
# package is installed (it isn't), so axes was keying every lockout on the
# proxy's IP: one attacker's 10 failures 429'd auth for ALL users at once.
# The callable degrades cleanly in local dev/tests (no proxy headers →
# REMOTE_ADDR), so it is set unconditionally.
AXES_CLIENT_IP_CALLABLE = "core.ip.get_client_ip"



# Media files (user-uploaded files) — served from S3
MEDIA_URL = f'https://{os.getenv("BUCKETEER_BUCKET_NAME")}.s3.amazonaws.com/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = '/web/portal/dashboard/'
LOGOUT_REDIRECT_URL = '/'


# Procrastinate config. The worker process is started by
# `python manage.py procrastinate worker`. It uses the same Postgres
# connection as Django (DATABASES['default']) via procrastinate.contrib.django.
# Periodic tasks are declared with @app.periodic(cron=...) decorators on
# the task functions themselves; there's no central schedule dict.
PROCRASTINATE_TIMEZONE = "America/New_York"

CACHES = {
    "default": {
        # DatabaseCache: stores cache entries in Postgres (django_cache table).
        # Created by `python manage.py createcachetable` (runs in the
        # entrypoint). Throughput is ~100 ops/day on this app, so this is
        # invisible on the DB.
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
        "KEY_PREFIX": "mdproject_cache",
    },
    # Per-worker in-process cache. Zero network — for hot reference data
    # that's read on nearly every request and changes rarely (sports,
    # leagues, sports-dropdown contents, market type lists, etc.).
    # Trade-off: each gunicorn worker has its own copy, so a write isn't
    # visible to other workers until their TTL expires. Use ONLY for
    # data where eventual consistency on the order of minutes is fine.
    # Read with: cache.cache["local"].get(...) / set(...).
    "local": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "mdproject-local",
        "TIMEOUT": 300,
        "OPTIONS": {
            "MAX_ENTRIES": 5000,
            "CULL_FREQUENCY": 3,
        },
    },
}


# SSL/TLS settings
# SECURE_SSL_REDIRECT defaults to True (correct behind a TLS-terminating
# proxy that forwards X-Forwarded-Proto: https). Override via env to
# False if the upstream proxy strips/skips the header — otherwise Django
# returns 301 to https://... on every request and the browser ends up in
# a redirect loop (since the inbound was already HTTPS upstream).
SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True") == "True"
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'
# Behind-proxy support — Coolify's Traefik (and most reverse proxies) put
# the original scheme into ``X-Forwarded-Proto``. Without this, Django's
# ``request.is_secure()`` returns False even on HTTPS requests, which
# breaks ``SECURE_SSL_REDIRECT`` (infinite loop) and makes secure cookies
# look insecure. Trusts ONLY this header from a single proxy hop.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

# ---------------------------------------------------------------------------
# Content-Security-Policy (S-7) — django-csp, ENFORCED.
#
# All scripts/styles/fonts/images are self-hosted (Bootstrap, bootstrap-icons,
# Alpine CSP build, Chart.js, Inter all vendored), and the portal/public surface
# is fully inline-script-free (no inline <script>, no on* handlers, no
# javascript: URIs — all externalized; the Alpine CSP build needs no eval). So
# `script-src 'self'` is STRICT: no 'unsafe-inline', no 'unsafe-eval'. This blocks
# inline-script XSS, external-origin scripts, and eval entirely — plus plugins
# (object-src none), framing (frame-ancestors none), base-tag hijack, off-origin
# form posts, and any off-origin style/img/font/fetch.
#
# style-src keeps 'unsafe-inline' — inline `style=""` attributes are pervasive and
# far lower XSS risk than scripts; tightening that is a separate, optional pass.
# `<script type="application/json">` data blocks (json_script) are non-executable
# and unaffected by script-src.
#
# report-uri stays so any enforced block (e.g. someone re-adds a CDN link or an
# inline handler) surfaces at /csp-report/. Admin/silk are excluded (Jazzmin/
# AdminLTE are inline+CDN heavy and out of scope).
# ---------------------------------------------------------------------------
CONTENT_SECURITY_POLICY = {
    "EXCLUDE_URL_PREFIXES": ["/admin/", "/silk/"],
    "DIRECTIVES": {
        "default-src": ["'self'"],
        # Cloudflare Browser Insights / Web Analytics auto-injects beacon.min.js
        # from static.cloudflareinsights.com and POSTs RUM data to
        # cloudflareinsights.com — both origins must be allowed or the beacon
        # is blocked (script-src for the load, connect-src for the report).
        #
        # Matomo (self-hosted at pmat.warforaterra.com) needs the same pair:
        # script-src for matomo.js, connect-src for the matomo.php tracking
        # calls (XHR/sendBeacon), plus img-src for the <img> pixel fallback
        # the tracker uses when XHR is unavailable. The bootstrap snippet
        # itself is externalized to static/js/matomo-init.js (loaded from the
        # public + portal base templates) because inline scripts are blocked.
        "script-src": [
            "'self'",
            "https://static.cloudflareinsights.com",
            "https://pmat.warforaterra.com",
        ],
        "style-src": ["'self'", "'unsafe-inline'"],
        "img-src": [
            "'self'",
            "data:",
            "https://*.s3.amazonaws.com",
            "https://pmat.warforaterra.com",
        ],
        "font-src": ["'self'", "data:"],
        "connect-src": [
            "'self'",
            "https://cloudflareinsights.com",
            "https://pmat.warforaterra.com",
        ],
        "frame-ancestors": ["'none'"],
        "base-uri": ["'self'"],
        "form-action": ["'self'"],
        "object-src": ["'none'"],
        "report-uri": "/csp-report/",
    },
}

# CSRF requires the full origin (scheme + host) for any cross-domain POST.
# Coolify hosts the app on a custom domain — list it here via env so the
# admin / portal forms accept POSTs over HTTPS.
#
# Django 4.0+ rejects entries without a scheme at startup, so we filter
# empties AND auto-prefix ``https://`` when the operator pasted a bare
# hostname (a common copy-paste mistake from the ALLOWED_HOSTS format,
# which DOES accept bare hosts).
def _parse_csrf_origins(raw: str) -> list[str]:
    out: list[str] = []
    for o in raw.split(","):
        o = o.strip()
        if not o:
            continue
        if not o.startswith(("http://", "https://")):
            o = f"https://{o}"
        out.append(o)
    return out


CSRF_TRUSTED_ORIGINS = _parse_csrf_origins(
    os.environ.get("CSRF_TRUSTED_ORIGINS", "")
)

# The Alpine islands read the CSRF token from the cookie and echo it back as the
# X-CSRFToken header so SessionAuthentication's CSRF check passes on unsafe v1
# methods (plan 03/06). The token is NOT a session secret, so a JS-readable
# cookie is acceptable; CSRF defense rests on the cookie+header match plus
# SameSite=Lax. (Django's default for HTTPONLY is already False — set
# explicitly so a future default change can't silently break the islands.)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'

# Default storage routes user uploads to S3 (Bucketeer). WhiteNoise serves
# collected static files; using the non-manifest variant because Jazzmin's
# Bootstrap bundle references .map files that aren't shipped — the manifest
# storage fails collectstatic post-processing on those references.
STORAGES = {
    "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Debug-mode overrides — relax cookie / redirect hardening so HTTP-only
# local dev keeps working. Database SSL is NOT touched: the driver honors
# whatever sslmode (or absence) is in DATABASE_URL, so local Postgres
# without SSL needs sslmode=disable in the URL, and prod / hosted Postgres
# keeps its require/verify-full unchanged when DEBUG is flipped on for
# an investigation.
if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Paradise Sports Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Paradise Sports",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Paradise Sports",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "/logo/paradise_logo_2_normal_100x100.png",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "/logo/paradise_logo_2_normal_100x100.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": "/logo/paradise_logo_2_normal_100x100.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": None,

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "/logo/paradise_logo_2_normal_100x100.png",

    # Welcome text on the login screen
    "welcome_sign": "Paradise Sports",

    # Copyright on the footer
    "copyright": "Paradise Sports",

    # List of model admins to search from the search bar, search bar omitted if excluded
    # If you want to use a single search field you dont need to use a list, you can use a simple string
    "search_model": ["core_user.User", "core_tournament.Tournament"],

    # No user_avatar: dropping this key flips Jazzmin to render a generic
    # font-awesome user icon in the admin sidebar instead of falling back
    # to AdminLTE's stock user2-160x160.jpg whenever an admin user lacks
    # an avatar (most of them — avatars are a portal-side concept).

    ############
    # Top Menu #
    ############

    # Links to put along the top menu.
    # Each item can use:
    #   url        — a named URL (reversed) or an absolute path like "/admin/dashboard/"
    #   model      — "app_label.ModelName" (Jazzmin builds the admin URL)
    #   app        — "app_label" to render a dropdown of every model in that app
    #   name       — label; optional for model/app items
    #   permissions — list of perm codenames that must all pass
    #   new_window — True to open in a new tab
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Dashboard", "url": "/admin/dashboard/", "permissions": ["auth.view_user"]},
        # Project status — worker liveness + DB / Redis / aggregator health
        # + live beat schedule + recent task results. Gated to staff via
        # @staff_member_required on the view itself; the permission check
        # below just hides the link from non-staff so it doesn't even appear.
        {"name": "Status", "url": "/admin/status/", "permissions": ["auth.view_user"]},
        {"name": "Waitlist", "url": "/admin/core_auth/waitlistentry/", "permissions": ["auth.view_user"]},
        {"name": "Portal", "url": "/web/portal/dashboard/", "new_window": True, "permissions": ["auth.view_user"]},
        # Stripe config introspection + one-click webhook endpoint
        # creation. Staff-gated at the view level via
        # @staff_member_required; the perm here just hides the link.
        {"name": "Stripe Setup", "url": "/admin/stripe-setup/", "permissions": ["auth.view_user"]},
    ],

    #############
    # User Menu #
    #############

    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    "usermenu_links": [
        {"name": "Portal", "url": "/web/portal/dashboard/", "new_window": True},
        {"model": "core_user.User"},
    ],

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [],

    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        "core_tournament", "core_match", "core_game", "core_event",
        "core_user", "core_auth", "core_mail",
        "auth", "django_celery_beat", "django_celery_results",
    ],

    # Custom links to append to app groups, keyed on app name.
    "custom_links": {},

    # Custom icons for side menu apps/models. See https://fontawesome.com/icons.
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core_user.User": "fas fa-user",
        "core_auth": "fas fa-clipboard-list",
        "core_auth.WaitlistEntry": "fas fa-clipboard-list",
        "core_tournament": "fas fa-trophy",
        "core_tournament.Tournament": "fas fa-trophy",
        "core_tournament.Player": "fas fa-user-tag",
        "core_tournament.Round": "fas fa-layer-group",
        "core_match": "fas fa-dice",
        "core_match.Match": "fas fa-dice",
        "core_match.TieBreaker": "fas fa-balance-scale",
        "core_game": "fas fa-gamepad",
        "core_event": "fas fa-calendar-alt",
        "core_event.Event": "fas fa-calendar-alt",
        "core_event.Team": "fas fa-shield-alt",
        "core_event.Sport": "fas fa-futbol",
        "core_event.Market": "fas fa-chart-line",
        "core_mail": "fas fa-envelope",
        "core_mail.Notification": "fas fa-bell",
        "core_mail.Invite": "fas fa-paper-plane",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    "custom_css": "admin/css/jazzmin_overrides.css",
    "custom_js": None,
    # Whether to link font from fonts.googleapis.com (use custom_css to supply font otherwise)
    "use_google_fonts_cdn": True,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "core_user.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}





# ---------------------------------------------------------------------------
# Aggregator integration (plan §7.4 cutover)
#
# Phase 2 (dual-write): leave USE_AGGRIGATOR=False; both pipelines run.
# Phase 3 (cutover):    flip USE_AGGRIGATOR=True; legacy crons disabled.
# Phase 4 (cleanup):    remove the dead SGO ingestion code from this repo.
#
# Read endpoints on the aggregator are public — no auth needed on the
# outbound HTTP client. AGGRIGATOR_WEBHOOK_SECRET is the HMAC signing secret
# shared with the aggregator (its AGG_WEBHOOK_SECRET); used only on the
# inbound webhook receiver at /sportgameodds/webhook.
# ---------------------------------------------------------------------------

USE_AGGRIGATOR = os.environ.get("USE_AGGRIGATOR", "False").lower() in ("1", "true", "yes")

# Admin 2FA enforcement (plan §7.3 item 9 phase 1). When true, the Django
# admin uses OTPAdminSite — staff must enter a TOTP code at login, and a
# user with NO enrolled device cannot log in to admin at all. Rollout order
# matters (same transitional-flag pattern as AGG_REQUIRE_KEY_FOR_READS):
#   1. deploy with the flag off,
#   2. enroll a TOTP device for each staff user (admin → OTP_TOTP → Add,
#      scan the qrcode link with an authenticator app),
#   3. set ADMIN_REQUIRE_OTP=true and redeploy.
ADMIN_REQUIRE_OTP = os.environ.get("ADMIN_REQUIRE_OTP", "").strip().lower() in ("1", "true", "yes", "on")
AGGRIGATOR_BASE_URL = os.environ.get("AGGRIGATOR_BASE_URL", "http://localhost:8001")
AGGRIGATOR_WEBHOOK_SECRET = os.environ.get("AGGRIGATOR_WEBHOOK_SECRET", "")

# Single service-tenant key for ALL outbound aggregator calls (plan §6.4,
# roadmap Phase 2). Minted once by the aggregator's
# scripts/provision_service_tenant.py; per-user keys are no longer issued
# or stored. Per-user data calls (bets) assert the acting user via
# X-Acting-User: <User.public_id> — only this key may assert.
AGGRIGATOR_SERVICE_KEY = os.environ.get("AGGRIGATOR_SERVICE_KEY", "").strip()

# HMAC secret for the OUTBOUND Paradise channel (MDProject → aggrigator
# /v1/internal/*). Same value as the aggrigator's AGG_PARADISE_SECRET.
# Separate from AGGRIGATOR_WEBHOOK_SECRET on purpose — opposite
# directions, separate trust scopes. See subscription-plan/07-security.md.
PARADISE_SECRET = os.environ.get("PARADISE_SECRET", "")

# ---------------------------------------------------------------------------
# Stripe — subscription billing.
# ---------------------------------------------------------------------------
# STRIPE_SECRET_KEY: sk_test_... in dev, sk_live_... in prod. Prefer a
#   RESTRICTED key (Stripe Dashboard → API keys → Restricted keys) with
#   only the scopes we need (Customer/Subscription/Product/Price/
#   Checkout.Session/BillingPortal write, Events read).
# STRIPE_WEBHOOK_SECRET: whsec_... from `stripe listen` (dev) or from
#   Dashboard → Developers → Webhooks → your endpoint (prod). Used to
#   verify Stripe-signed webhooks at /billing/stripe/webhook.
# STRIPE_API_VERSION: pin so a Stripe-side surface change can't break us.
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
STRIPE_API_VERSION = os.environ.get("STRIPE_API_VERSION", "2025-07-30.basil")

# PLATFORM_COST: monthly PRO-plan price in dollars (e.g. 2.99). The
# ``manage.py sync_platform_cost`` command reads this and reconciles
# the PRO Plan row's ``amount_cents`` — saving the Plan triggers the
# post_save signal that pushes the new Price to Stripe.
# Empty / unset = leave the Plan row alone (the previous value stands).
_raw_platform_cost = (os.environ.get("PLATFORM_COST") or "").strip()
if _raw_platform_cost:
    from decimal import Decimal as _D, InvalidOperation as _InvalidOp
    try:
        PLATFORM_COST_CENTS = int(round(_D(_raw_platform_cost) * 100))
    except (_InvalidOp, ValueError):
        # Bad value (typo, non-numeric) — surface as None so the sync
        # command can warn rather than silently rounding to zero.
        PLATFORM_COST_CENTS = None
else:
    PLATFORM_COST_CENTS = None

# ANALYTICS_FREE_FOR_ALL: platform-wide kill-switch. When "1", every
# logged-in user is treated as entitled to analytics regardless of their
# Subscription plan/status. The billing/upgrade pages swap copy and hide
# the checkout CTA. Stripe catalog, existing PRO subs, and webhooks are
# untouched — flipping back to "0" restores the normal gate.
ANALYTICS_FREE_FOR_ALL = os.environ.get("ANALYTICS_FREE_FOR_ALL", "0") == "1"

# --- Fake paywall (roadmap Phase 3 §4, decision D-3) -----------------------
# Only meaningful while ANALYTICS_FREE_FOR_ALL is on: FREE users see a
# paywall interstitial (once per session) before being let through anyway.
# Impressions/clicks land in core_metrics.ProductEvent — the click-through
# rate is the willingness-to-pay signal that prices PRO (decision D-10).
FAKE_PAYWALL_ENABLED = os.environ.get("FAKE_PAYWALL_ENABLED", "").strip().lower() in ("1", "true", "yes", "on")
# Display-only price on the interstitial (D-3 recommends $7–10/mo). The
# real Stripe price stays on the Plan row; this is what testers SEE.
PAYWALL_DISPLAY_PRICE = os.environ.get("PAYWALL_DISPLAY_PRICE", "$9/mo")

# Pick-email coalescing window (plan §7.1 #5): the first pick in a match
# queues a summary email this many seconds out; further picks inside the
# window are absorbed into that one send.
PICK_EMAIL_DEBOUNCE_SECONDS = int(os.environ.get("PICK_EMAIL_DEBOUNCE_SECONDS", "180"))

# Fail fast in production if aggregator is enabled but the webhook secret
# is missing — without it, inbound deliveries get rejected for signature
# mismatch (or 503'd if the receiver guards explicitly).
if not DEBUG and USE_AGGRIGATOR and not AGGRIGATOR_WEBHOOK_SECRET:
    raise RuntimeError("AGGRIGATOR_WEBHOOK_SECRET must be set when USE_AGGRIGATOR=True")
# Same fail-fast for Paradise — without it, signup signal + Stripe
# webhook handler raise ImproperlyConfigured on every fire.
if not DEBUG and USE_AGGRIGATOR and not PARADISE_SECRET:
    raise RuntimeError("PARADISE_SECRET must be set when USE_AGGRIGATOR=True")
# And for the service key — without it every analytics/bets proxy call
# goes out keyless: 401s on keyed routes, WARNING spam on the rest.
# Provision via the aggregator's scripts/provision_service_tenant.py.
if not DEBUG and USE_AGGRIGATOR and not AGGRIGATOR_SERVICE_KEY:
    raise RuntimeError("AGGRIGATOR_SERVICE_KEY must be set when USE_AGGRIGATOR=True")


# ---------------------------------------------------------------------------
# Logging — structured stdout for container log aggregation.
# ---------------------------------------------------------------------------
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "core": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------------
# django-silk — in-process request/SQL profiler.
#
# Off by default. Flip on per-environment with SILK_ENABLED=True. Stores
# captured requests in Postgres (same DB unless you give silk its own),
# so leave it OFF in prod long-term — turn it on for a debug session,
# investigate, turn it off.
#
# Auth: SILKY_AUTHENTICATION + SILKY_AUTHORISATION gate /silk/ behind a
# logged-in is_staff user (same access as Django admin). Without these,
# the dashboard exposes every captured request body, header, and SQL
# query to anyone who guesses the URL — including cookies, auth tokens,
# and webhook payloads. Do not relax.
#
# Sampling: SILK_INTERCEPT_PERCENT env (default 5) keeps overhead and
# storage bounded. Bump to 100 only on local / staging while reproducing
# a specific slow page.
# ---------------------------------------------------------------------------
SILK_ENABLED = os.environ.get("SILK_ENABLED", "").strip().lower() in ("1", "true", "yes", "on")

if SILK_ENABLED:
    INSTALLED_APPS += ["silk"]
    # Insert silk middleware right after AuthenticationMiddleware so
    # request.user is populated when silk evaluates SILKY_AUTHORISATION,
    # but still above the project's custom middleware so their timings
    # are captured in the silk waterfall.
    _auth_mw = "django.contrib.auth.middleware.AuthenticationMiddleware"
    _silk_mw = "silk.middleware.SilkyMiddleware"
    if _auth_mw in MIDDLEWARE:
        MIDDLEWARE.insert(MIDDLEWARE.index(_auth_mw) + 1, _silk_mw)
    else:
        MIDDLEWARE.append(_silk_mw)

    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True
    # Belt-and-braces: even staff users only see /silk/ if they're also
    # superuser. Loosen to `u.is_staff` if a non-superuser admin needs in.
    SILKY_PERMISSIONS = lambda u: u.is_authenticated and u.is_superuser

    SILKY_HIDE_COOKIES = True
    SILKY_MAX_REQUEST_BODY_SIZE = 4096   # bytes; truncate huge POSTs
    SILKY_MAX_RESPONSE_BODY_SIZE = 4096
    SILKY_META = True  # show silk's own overhead per request

    # Skip noise: silk's own UI assets, Django static, healthz probes,
    # and the silk dashboard itself. Without this, /silk/ ends up
    # mostly displaying captures of /silk/ — recursive and useless.
    SILKY_IGNORE_PATHS = [
        "/static/",
        "/silk/",
        "/healthz",
        "/robots.txt",
    ]

    # cProfile-level Python timings on each captured request. The
    # "Profile" tab in /silk/<request>/ is empty without this. Combined
    # with SILK_INTERCEPT_PERCENT this only fires on the sampled
    # requests, so the cProfile overhead is bounded. BINARY=True writes
    # a .prof file you can download and open in snakeviz for a flame
    # graph view.
    SILKY_PYTHON_PROFILER = True
    # Binary .prof export is OFF — Silk hardcodes the write to
    # FileSystemStorage(MEDIA_ROOT), ignoring STORAGES["default"]=S3. On
    # Railway/Coolify the container has no writable /app/media (media/ is
    # in .dockerignore + the FS is ephemeral anyway), so enabling this
    # makes every silk-sampled request 500 with FileNotFoundError. The
    # in-UI profile waterfall still renders without it.
    SILKY_PYTHON_PROFILER_BINARY = False

    try:
        SILKY_INTERCEPT_PERCENT = int(os.environ.get("SILK_INTERCEPT_PERCENT", "5"))
    except ValueError:
        SILKY_INTERCEPT_PERCENT = 5


# ---------------------------------------------------------------------------
# Error tracking — GlitchTip via sentry-sdk
#
# Gated on SENTRY_DSN: empty/missing = sentry stays inert (local dev
# untouched). One init covers BOTH web and worker — the Procrastinate
# worker boots via `manage.py procrastinate worker`, which loads these
# settings. There is no official Procrastinate integration; the Django
# integration's ERROR-level logging capture picks up task failures.
#
# ENVIRONMENT separates prod/staging/dev events in GlitchTip (settings
# otherwise only know the DEBUG flag). SOURCE_COMMIT is injected as a
# build arg by Coolify and baked into the image (see Dockerfile.web /
# Dockerfile.worker) so every event carries the deployed commit SHA.
# ---------------------------------------------------------------------------
SENTRY_DSN = os.environ.get("SENTRY_DSN", "").strip()

if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get("ENVIRONMENT", "dev"),
        release=os.environ.get("SOURCE_COMMIT") or None,
        # Errors only — no request bodies, no user PII, no perf tracing.
        # Revisit traces_sample_rate if perf monitoring is ever wanted.
        send_default_pii=False,
        traces_sample_rate=0,
    )
