# Generated by Django 5.2.13 on 2026-05-17 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('interval', models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=8)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'billing_plan',
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('stripe_event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('body_excerpt', models.TextField()),
                ('apply_error', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'billing_stripe_webhook_event',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'trialing'), ('active', 'active'), ('past_due', 'past_due'), ('unpaid', 'unpaid'), ('canceled', 'canceled'), ('incomplete', 'incomplete'), ('incomplete_expired', 'incomplete_expired')], default='active', max_length=24)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_billing.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_subscription',
            },
        ),
    ]
