# Generated by Django 5.0.3 on 2024-08-10 05:20

import core.event.models.team
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sport_key', models.CharField(max_length=255)),
                ('sport_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('commence_time', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('scores', models.CharField(default=None, max_length=255, null=True)),
                ('winner', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'core_event_event',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('has_outrights', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_sport',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('team_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('logo_url', models.ImageField(blank=True, null=True, upload_to=core.event.models.team.upload_to_path)),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': "'core.team'",
            },
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmakers', to='core_event.event')),
            ],
            options={
                'db_table': 'core.bookmaker',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('last_update', models.DateTimeField()),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='core_event.bookmaker')),
            ],
            options={
                'db_table': 'core.market',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('point', models.FloatField(null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='core_event.market')),
            ],
            options={
                'db_table': 'core.outcome',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='away_team_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team_team', to='core_event.team'),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team_team', to='core_event.team'),
        ),
    ]
