# Generated by Django 5.0 on 2023-12-30 02:51
import uuid
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # Dependencies (other migrations this one depends on)
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                # Fields for the Event model
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sport_key', models.CharField(max_length=255)),
                ('sport_title', models.CharField(max_length=255)),
                ('commence_time', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('scores', models.CharField(max_length=255, null=True)),
                ('winner', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                # Fields for the Sport model
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('has_outrights', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('sport_key', models.CharField(max_length=255)),
                ('sport_title', models.CharField(max_length=255)),
                ('commence_time', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('scores', models.CharField(max_length=255, null=True)),
                ('winner', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
