# Generated by Django 5.0.3 on 2024-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bookmaker", name="core.bookma_event_i_56f190_idx",
        ),
        migrations.RemoveField(model_name="bookmaker", name="event",),
        migrations.AddIndex(
            model_name="bookmaker",
            index=models.Index(
                fields=["last_update"], name="core.bookma_last_up_f97a4c_idx"
            ),
        ),
    ]
