# Generated by Django 5.0.3 on 2024-10-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmaker", name="key", field=models.CharField(max_length=255),
        ),
    ]
