# Generated by Django 5.0 on 2024-03-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
