# Generated by Django 5.0.3 on 2026-04-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='scope',
            field=models.CharField(choices=[('FULL_GAME', 'Full Game'), ('H1', 'H1'), ('H2', 'H2'), ('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4'), ('OVERTIME', 'Overtime'), ('PERIOD_N', 'Period N'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('SHOOTOUT', 'Shootout')], default='FULL_GAME', max_length=16),
        ),
    ]
