# Generated by Django 5.0.3 on 2024-08-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='core_event',
        ),
    ]
