# Generated by Django 5.0.3 on 2024-07-28 20:35

import core.event.models.team
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to=core.event.models.team.upload_to_path),
        ),
        migrations.AlterModelTable(
            name='team',
            table="'core.team'",
        ),
    ]
