# Generated by Django 5.0 on 2024-01-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scores',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
