# Generated by Django 5.0.3 on 2024-08-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_bookmaker_market_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmaker',
            name='last_update',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='last_update',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='bookmaker',
            index=models.Index(fields=['event', 'last_update'], name='core.bookma_event_i_56f190_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['bookmaker', 'last_update'], name='core.market_bookmak_8948ec_idx'),
        ),
        migrations.AddIndex(
            model_name='outcome',
            index=models.Index(fields=['market', 'name'], name='core.outcom_market__33cccf_idx'),
        ),
    ]
