# Generated by Django 5.0.3 on 2024-10-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0002_alter_bookmaker_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="market",
            name="bookmaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="markets",
                to="core_event.bookmaker",
            ),
        ),
    ]
