# Generated by Django 5.0.3 on 2026-04-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_alter_market_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selection',
            name='settlement_source',
            field=models.CharField(blank=True, choices=[('PROVIDER', 'Provider'), ('COMPUTED', 'Computed'), ('MANUAL', 'Manual')], max_length=16),
        ),
        migrations.AddField(
            model_name='selection',
            name='settlement_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('PUSH', 'Push'), ('VOID', 'Void')], db_index=True, default='PENDING', max_length=8),
        ),
        migrations.AddIndex(
            model_name='selection',
            index=models.Index(fields=['settlement_status', 'market'], name='core_select_settlem_994b7a_idx'),
        ),
    ]
