# Generated by Django 5.0.3 on 2024-08-10 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_alter_event_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='core_event_event',
        ),
    ]
