# Generated by Django 5.0.3 on 2024-09-27 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0002_remove_bookmaker_core_bookma_event_i_56f190_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="market", name="core.market_bookmak_8948ec_idx",
        ),
        migrations.AddField(
            model_name="market",
            name="event",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="market_event",
                to="core_event.event",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="market",
            index=models.Index(
                fields=["bookmaker", "last_update", "event"],
                name="core.market_bookmak_62c739_idx",
            ),
        ),
    ]
