# Generated by Django 5.0.3 on 2024-08-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_bookmaker_market_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
