# Generated by Django 5.0 on 2024-01-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_alter_event_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
