# Generated by Django 5.2.14 on 2026-06-16 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_widen_event_id_and_webhook_received'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamLogo',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='logo', serialize=False, to='core_event.team')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=64, null=True)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('etag', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=16)),
                ('source', models.CharField(default='aggregator', max_length=32)),
                ('fetched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_team_logo',
            },
        ),
    ]
