# Generated by Django 5.2.14 on 2026-06-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0003_teamlogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='logo_url',
        ),
    ]
