# Generated by Django 5.0.3 on 2024-09-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_event",
            "0003_alter_bookmaker_last_update_alter_market_last_update_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scores",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
