# Generated by Django 5.0.3 on 2024-11-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0005_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="winner",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
