# Generated by Django 5.0.3 on 2024-08-26 01:04

from django.db import migrations

def create_portal_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Portal Group')

class Migration(migrations.Migration):

    dependencies = [
        ("commands", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_portal_group),
    ]
