# Generated by Django 5.2.14 on 2026-06-14 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_match', '0004_tiebreaker_predictions_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='DRAFT', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_ranking_season',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('global_points', models.IntegerField(default=0)),
                ('lifetime_wins', models.IntegerField(default=0)),
                ('lifetime_losses', models.IntegerField(default=0)),
                ('lifetime_draws', models.IntegerField(default=0)),
                ('lifetime_games', models.IntegerField(default=0)),
                ('all_time_rating', models.FloatField(default=1200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_ranking_progress',
                'indexes': [models.Index(fields=['-global_points'], name='core_rankin_global__78462c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DIVISION_WINNER', 'Division winner'), ('TOP_THREE', 'Top 3 finish'), ('PERFECT_WEEK', 'Perfect week'), ('STREAK', 'Streak milestone')], max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges', to='core_ranking.season')),
            ],
            options={
                'db_table': 'core_ranking_badge',
                'indexes': [models.Index(fields=['user', '-earned_at'], name='core_rankin_user_id_7d91d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SeasonParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=1200)),
                ('season_points', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('potd_wins', models.IntegerField(default=0)),
                ('potd_picks', models.IntegerField(default=0)),
                ('division', models.IntegerField(default=1)),
                ('final_rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='core_ranking.season')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_ranking_participation',
                'indexes': [models.Index(fields=['season', '-season_points'], name='core_rankin_season__b0d0ab_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'season'), name='uniq_user_season')],
            },
        ),
        migrations.CreateModel(
            name='XpEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('MATCH_COMPLETED', 'Match completed'), ('MATCH_WIN', 'Match win bonus'), ('GOLDEN_HIT', 'Golden pick hit'), ('POTD_PICK', 'POTD pick made'), ('POTD_WIN', 'POTD pick won'), ('POTD_STREAK', 'POTD streak milestone'), ('DUEL_WON', 'Duel won'), ('SEASON_FINISH', 'Season finish')], max_length=20)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='core_match.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_ranking_xp_event',
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_rankin_user_id_c3ea2f_idx')],
            },
        ),
    ]
