# Generated by Django 5.2.14 on 2026-06-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogress',
            name='current_division',
            field=models.IntegerField(default=1),
        ),
    ]
