# Generated by Django 5.2.14 on 2026-06-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_potd', '0001_initial_potd'),
        ('core_ranking', '0002_playerprogress_current_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpevent',
            name='potd_pick',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_events', to='core_potd.dailypick'),
        ),
    ]
