# Generated by Django 5.2.14 on 2026-06-13 01:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_event', '0002_widen_event_id_and_webhook_received'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickOfDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('lock_time', models.DateTimeField()),
                ('manually_curated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potd_days', to='core_event.event')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potd_days', to='core_event.market')),
            ],
            options={
                'verbose_name': 'Pick of the Day',
                'verbose_name_plural': 'Picks of the Day',
                'db_table': 'core_potd',
            },
        ),
        migrations.CreateModel(
            name='DailyPick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost'), ('VOID', 'Void')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_picks', to='core_event.selection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_picks', to=settings.AUTH_USER_MODEL)),
                ('potd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='core_potd.pickofday')),
            ],
            options={
                'db_table': 'core_daily_pick',
                'constraints': [models.UniqueConstraint(fields=('user', 'potd'), name='uq_daily_pick_user_potd')],
            },
        ),
    ]
