# Generated by Django 5.0.3 on 2024-10-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status", options={"ordering": ["position"]},
        ),
        migrations.AddField(
            model_name="status",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
