# Generated by Django 5.0.3 on 2024-10-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_alter_status_options_status_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="email",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
