# Generated by Django 5.0.3 on 2024-09-27 19:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("description", models.TextField(blank=True)),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("registered", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(blank=True, null=True)),
                ("activated", models.BooleanField(default=False)),
                ("admin_granted_access", models.BooleanField(default=False)),
            ],
        ),
    ]
