# Generated by Django 5.0.3 on 2024-06-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
