# Generated by Django 5.0 on 2024-03-23 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0002_waitlist_created_waitlist_updated_alter_waitlist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlistentry',
            name='waitlist',
        ),
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
