# Generated by Django 5.0.3 on 2024-07-23 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='core_mail_notification',
        ),
    ]
