# Generated by Django 5.0.3 on 2024-10-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_mail", "0003_invite"),
    ]

    operations = [
        migrations.AlterModelTable(name="invite", table="core_invite",),
    ]
