# Generated by Django 5.2.13 on 2026-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mail', '0006_alter_invite_obj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('match', 'Match'), ('friend', 'Friend')], max_length=20),
        ),
    ]
