# Generated by Django 5.2.14 on 2026-06-12 18:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mail', '0007_alter_invite_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='invite',
            name='state',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='sent', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('invite_type', models.CharField(default='friend', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_pending_invites',
            },
        ),
    ]
