# Generated by Django 5.2.14 on 2026-06-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_mail', '0008_phase4_phase5_invites_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
