# Generated by Django 5.2.14 on 2026-06-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_mail', '0009_notification_cleared_at_notification_read_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='cleared_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_at',
        ),
    ]
