# Generated by Django 5.0.3 on 2024-10-15 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("obj_id", models.UUIDField()),
                (
                    "type",
                    models.CharField(
                        choices=[("tournament", "Tournament"), ("match", "Match")],
                        max_length=20,
                    ),
                ),
                ("accepted", models.BooleanField(default=False)),
                ("accepted_date", models.DateTimeField(null=True)),
                ("invited_date", models.DateTimeField(null=True)),
                ("state", models.CharField(default="sent", max_length=20)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "core_invite",},
        ),
    ]
