# Generated by Django 5.0.3 on 2024-10-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_portal", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Invite",),
    ]
