# Generated by Django 5.0.3 on 2024-07-27 17:02

import core.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to=core.user.models.user_avatar_upload_path),
        ),
    ]
