# Generated by Django 5.0.3 on 2024-09-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_writer",
            field=models.BooleanField(default=False),
        ),
    ]
