# Generated by Django 5.0.3 on 2024-07-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_link',
            field=models.BooleanField(default=False),
        ),
    ]
