# Generated by Django 5.0.3 on 2024-10-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='writer_descritption',
            field=models.TextField(null=True),
        ),
    ]
