# Generated by Django 5.0.3 on 2024-08-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "00002_adding_portal_password"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="portal_password",),
    ]
