# Generated by Django 5.0.3 on 2024-10-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_user_writer_descritption'),
    ]

    operations = [
    ]
