# Generated by Django 5.0.3 on 2024-10-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0004_alter_user_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='writer_descritption',
            new_name='writer_description',
        ),
    ]
