# Generated by Django 5.0.3 on 2024-10-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0005_rename_writer_descritption_user_writer_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="_stripe_account_id",
            field=models.BinaryField(null=True),
        ),
    ]
