# Generated by Django 5.0.3 on 2024-10-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_user", "0006_user__stripe_account_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="_stripe_account_id",),
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
