# Generated by Django 5.0.3 on 2024-10-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0007_remove_user__stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
