# Generated by Django 5.0.3 on 2026-04-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0009_user_friend_code_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='writer_description',
        ),
    ]
