# Generated by Django 5.0.3 on 2026-04-24 17:12

from django.db import migrations, models


def swap_created_updated(apps, schema_editor):
    User = apps.get_model('core_user', 'User')
    table = User._meta.db_table
    # PostgreSQL and SQLite evaluate the RHS against the old row before any
    # assignment, so this single statement swaps the two columns correctly.
    schema_editor.execute(
        f'UPDATE "{table}" SET created = updated, updated = created;'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0010_remove_user_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(swap_created_updated, reverse_code=swap_created_updated),
    ]
