# Generated by Django 5.2.13 on 2026-05-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0012_alter_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aggrigator_api_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='aggrigator_external_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
