# Generated by Django 5.2.14 on 2026-06-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0015_user_email_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='potd_best_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='potd_current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='potd_last_pick_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
