# Generated by Django 5.2.14 on 2026-06-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0019_user_home_away_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clock_format',
            field=models.CharField(choices=[('12h', '12-hour'), ('24h', '24-hour')], default='12h', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
