# Generated by Django 5.0.3 on 2024-09-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog_writer', '0001_initial'),
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core_event.outcome'),
        ),
    ]
