# Generated by Django 5.0.3 on 2024-10-06 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_blog_writer", "0002_article_outcome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Set the monthly price for the subscription",
                        max_digits=10,
                    ),
                ),
                (
                    "writer",
                    models.OneToOneField(
                        limit_choices_to={"is_writer": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
