# Generated by Django 5.0.3 on 2024-10-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_blog_writer", "0003_subscriptionplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Publish?"),
        ),
    ]
