# Generated by Django 5.0.3 on 2024-09-17 17:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_market', to='core_event.market')),
                ('owner_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_owner_outcome', to='core_event.outcome')),
                ('player_2_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_player_2_outcome', to='core_event.outcome')),
            ],
            options={
                'db_table': 'core.bet',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_id', models.CharField(default='0', max_length=200)),
                ('commence_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('deadline_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('home_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('away_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('winner', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('owner_choice', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('player_2_choice', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_bet', to='core_game.bet')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core_event.event')),
            ],
            options={
                'db_table': 'core.game',
            },
        ),
    ]
