# Generated by Django 5.0 on 2023-12-31 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commence_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('deadline_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('home_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('away_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('winner', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('owner_choice', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('player_2_choice', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_game', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_game', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
