# Generated by Django 5.2.13 on 2026-04-29 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_widen_event_id_and_webhook_received'),
        ('core_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='locked_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core_event.market'),
        ),
    ]
