# Generated by Django 5.0 on 2023-12-31 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0001_initial'),
        ('core_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='core_event.event'),
        ),
    ]
