# Generated by Django 5.2.14 on 2026-06-06 02:39
#
# The Golden Game is ownerless: it belongs to the match, both players pick
# on it independently. Existing golden rows (created with owner=player_1,
# player_2=player_2) are backfilled to NULL/NULL; sides derive from
# match.player_1 / match.player_2 from here on.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _null_golden_players(apps, schema_editor):
    Game = apps.get_model('core_game', 'Game')
    Game.objects.filter(is_golden=True).update(owner=None, player_2=None)


def _restore_golden_players(apps, schema_editor):
    Game = apps.get_model('core_game', 'Game')
    for game in Game.objects.filter(is_golden=True).select_related('match'):
        game.owner_id = game.match.player_1_id
        game.player_2_id = game.match.player_2_id
        game.save(update_fields=['owner', 'player_2'])


class Migration(migrations.Migration):

    dependencies = [
        ('core_event', '0002_widen_event_id_and_webhook_received'),
        ('core_game', '0002_bet_locked_market'),
        ('core_match', '0002_tiebreaker'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_game', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2_game', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(_null_golden_players, _restore_golden_players),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('is_golden', True)), fields=('match',), name='uq_game_one_golden_per_match'),
        ),
    ]
