# Generated by Django 5.0.3 on 2024-11-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_game", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bet",
            name="owner_outcome_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bet",
            name="player_2_outcome_correct",
            field=models.BooleanField(default=False),
        ),
    ]
