# Generated by Django 5.0.3 on 2024-09-05 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_event",
            "0003_alter_bookmaker_last_update_alter_market_last_update_and_more",
        ),
        ("core_game", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "correct_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_correct_outcome",
                        to="core_event.outcome",
                    ),
                ),
                (
                    "owner_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_owner_outcome",
                        to="core_event.outcome",
                    ),
                ),
                (
                    "player_2_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_player_2_outcome",
                        to="core_event.outcome",
                    ),
                ),
                (
                    "selected_outcome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bet_selected_outcome",
                        to="core_event.outcome",
                    ),
                ),
            ],
            options={"db_table": "core.bet",},
        ),
    ]
