# Generated by Django 5.0 on 2024-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='match_id',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
