# Generated by Django 5.0.3 on 2024-07-01 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='core.game',
        ),
    ]
