# Generated by Django 5.2.14 on 2026-06-13 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0003_golden_game_ownerless'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='golden_hit_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
