# Generated by Django 5.0.3 on 2024-09-06 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_game", "0003_bet"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="bet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="game_bet",
                to="core_game.bet",
            ),
        ),
    ]
