# Generated by Django 5.0.3 on 2024-11-12 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0005_reply"),
        ("core_game", "0003_bet_is_processed_bet_owner_outcome_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="core_event.event",
            ),
        ),
    ]
