# Generated by Django 5.0.3 on 2024-09-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_event",
            "0003_alter_bookmaker_last_update_alter_market_last_update_and_more",
        ),
        ("core_game", "0004_game_bet"),
    ]

    operations = [
        migrations.RemoveField(model_name="bet", name="correct_outcome",),
        migrations.RemoveField(model_name="bet", name="selected_outcome",),
        migrations.RemoveField(model_name="bet", name="type",),
        migrations.AddField(
            model_name="bet",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bet_market",
                to="core_event.market",
            ),
        ),
    ]
