# Generated by Django 5.0.3 on 2024-11-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_game", "0004_alter_game_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="is_owner_outcome_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bet",
            name="is_player_2_outcome_processed",
            field=models.BooleanField(default=False),
        ),
    ]
