# Generated by Django 5.0.3 on 2024-09-08 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_game", "0005_remove_bet_correct_outcome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="bet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
