# Generated by Django 5.0.3 on 2024-11-24 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_event", "0006_alter_event_winner"),
        ("core_game", "0005_bet_is_owner_outcome_processed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bet",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bet_market",
                to="core_event.market",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="owner_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bet_owner_outcome",
                to="core_event.outcome",
            ),
        ),
        migrations.AlterField(
            model_name="bet",
            name="player_2_outcome",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bet_player_2_outcome",
                to="core_event.outcome",
            ),
        ),
    ]
