# Generated by Django 5.0.3 on 2024-07-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog', '0001_initial'),
        ('core_event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core_event.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='highlight_link',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
