# Generated by Django 5.0.3 on 2024-09-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_blog", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Article",),
        migrations.DeleteModel(name="Tag",),
    ]
