# Generated by Django 5.0 on 2024-01-03 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_game', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_state', models.CharField(default='created', max_length=10)),
                ('player_1_score', models.IntegerField(default=0)),
                ('player_2_score', models.IntegerField(default=0)),
                ('player_1_game_1_completed', models.BooleanField(default=False)),
                ('player_1_game_2_completed', models.BooleanField(default=False)),
                ('player_1_game_3_completed', models.BooleanField(default=False)),
                ('player_1_game_4_completed', models.BooleanField(default=False)),
                ('player_1_game_5_completed', models.BooleanField(default=False)),
                ('player_2_game_1_completed', models.BooleanField(default=False)),
                ('player_2_game_2_completed', models.BooleanField(default=False)),
                ('player_2_game_3_completed', models.BooleanField(default=False)),
                ('player_2_game_4_completed', models.BooleanField(default=False)),
                ('player_2_game_5_completed', models.BooleanField(default=False)),
                ('golden_game_completed', models.BooleanField(default=False)),
                ('golden_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_golden_game_game', to='core_game.game')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_match', to=settings.AUTH_USER_MODEL)),
                ('player_1_game_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_1', to='core_game.game')),
                ('player_1_game_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_2', to='core_game.game')),
                ('player_1_game_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_3', to='core_game.game')),
                ('player_1_game_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_4', to='core_game.game')),
                ('player_1_game_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_5', to='core_game.game')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_match', to=settings.AUTH_USER_MODEL)),
                ('player_2_game_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_1', to='core_game.game')),
                ('player_2_game_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_2', to='core_game.game')),
                ('player_2_game_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_3', to='core_game.game')),
                ('player_2_game_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_4', to='core_game.game')),
                ('player_2_game_5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_5', to='core_game.game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_match', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
