# Generated by Django 5.0.3 on 2024-04-21 20:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_state', models.CharField(default='created', max_length=10)),
                ('match_type', models.CharField(default='public', max_length=10)),
                ('player_1_score', models.IntegerField(default=0)),
                ('player_2_score', models.IntegerField(default=0)),
                ('player_1_game_1_completed', models.BooleanField(default=False)),
                ('player_1_game_2_completed', models.BooleanField(default=False)),
                ('player_1_game_3_completed', models.BooleanField(default=False)),
                ('player_1_game_4_completed', models.BooleanField(default=False)),
                ('player_1_game_5_completed', models.BooleanField(default=False)),
                ('player_2_game_1_completed', models.BooleanField(default=False)),
                ('player_2_game_2_completed', models.BooleanField(default=False)),
                ('player_2_game_3_completed', models.BooleanField(default=False)),
                ('player_2_game_4_completed', models.BooleanField(default=False)),
                ('player_2_game_5_completed', models.BooleanField(default=False)),
                ('golden_game_completed', models.BooleanField(default=False)),
                ('golden_game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_golden_game_game', to='core_game.game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
