# Generated by Django 5.0 on 2024-01-03 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0002_initial'),
        ('core_match', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='golden_game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_golden_game_game', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_game_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_1', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_game_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_2', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_game_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_3', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_game_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_4', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_1_game_5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_1_game_5', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2_match', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_game_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_1', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_game_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_2', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_game_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_3', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_game_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_4', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_2_game_5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_player_2_game_5', to='core_game.game'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_match', to=settings.AUTH_USER_MODEL),
        ),
    ]
