# Generated by Django 5.2.14 on 2026-06-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_match', '0002_tiebreaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='format',
            field=models.CharField(choices=[('BLITZ', 'Blitz'), ('CLASSIC', 'Classic'), ('MARATHON', 'Marathon')], default='MARATHON', max_length=10),
        ),
    ]
