# Generated by Django 5.0.3 on 2024-07-15 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_game', '0003_alter_game_table'),
        ('core_match', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='golden_game',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='golden_game', to='core_game.game'),
        ),
    ]
