# Generated by Django 5.0.3 on 2024-07-16 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_match', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tiebreaker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_tiebreaker', to='core_match.tiebreaker'),
        ),
    ]
