# Generated by Django 5.0 on 2024-01-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_match', '0002_alter_match_golden_game_alter_match_player_1_game_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
