# Generated by Django 5.0.3 on 2024-11-13 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_game", "0005_bet_is_owner_outcome_processed_and_more"),
        ("core_match", "0003_alter_match_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiebreaker",
            name="golden_game",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiebreaker_golden_game",
                to="core_game.game",
            ),
        ),
        migrations.AddField(
            model_name="tiebreaker",
            name="owner_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tiebreaker",
            name="player_2_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tiebreaker", name="total", field=models.IntegerField(default=0),
        ),
    ]
