# Generated by Django 5.0.3 on 2024-07-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_match', '0003_match_tiebreaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
