# Generated by Django 5.0.3 on 2024-10-06 14:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_blog_client", "0001_initial"),
        ("core_blog_writer", "0003_subscriptionplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core_blog_writer.subscriptionplan",
            ),
            preserve_default=False,
        ),
    ]
