# Generated by Django 5.0.3 on 2024-10-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core_blog_client", "0002_subscription_end_date_subscription_plan"),
    ]

    operations = [
        migrations.RemoveField(model_name="subscription", name="end_date",),
        migrations.RemoveField(model_name="subscription", name="plan",),
    ]
