# Generated by Django 5.0.3 on 2024-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_blog_client', '0004_subscription_end_date_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
